export const CONFIG = {
  appName:         'Meme Capsule',
  tagline:         'One tap. One capsule drop. Pure chaos.',
  description:     'The randomest meme delivery app on Android. No algorithm. No feed. Just one button and pure unhinged entertainment.',
  playStoreUrl:    'https://play.google.com/store/apps/details?id=com.meme.capsule',
  packageId:       'com.meme.capsule',
  apiBase:         'https://meme-capsule-eww.pages.dev',
  formspreeId:     'xwlenwzr',
  gaId:            'G-8VMD4ZNQQK',
  adsenseClientId: 'ca-pub-2093403233028868',
  githubUrl:       'https://github.com/bbethical010-glitch/bbethical010-glitch.github.io',
  developerName:   'Pratham Pandey',
  contactEmail:    'memecapsule.app@gmail.com',
  siteUrl:         'https://memecapsule.wtf',
}
